In [2]:
# Dependencies
import pandas as pd

In [3]:
# Read in Kaggle dataset
netflix_all = pd.read_csv('netflix_titles.csv')
netflix_all.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [4]:
netflix_all = netflix_all[["title", "type", "director", "cast", "country", "release_year", "date_added", "rating", "listed_in"]].copy()
netflix_all

,title,type,director,cast,country,release_year,date_added,rating,listed_in
0,Norm of the North: King Sized Adventure,Movie,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,"September 9, 2019",TV-PG,"Children & Family Movies, Comedies"
1,Jandino: Whatever it Takes,Movie,NaN,Jandino Asporaat,United Kingdom,2016,"September 9, 2016",TV-MA,Stand-Up Comedy
2,Transformers Prime,TV Show,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,"September 8, 2018",TV-Y7-FV,Kids' TV
3,Transformers: Robots in Disguise,TV Show,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,"September 8, 2018",TV-Y7,Kids' TV
4,#realityhigh,Movie,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,"September 8, 2017",TV-14,Comedies
...,...,...,...,...,...,...,...,...,...
6229,Red vs. Blue,TV Show,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NaN,NR,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
6230,Maron,TV Show,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,NaN,TV-MA,TV Comedies
6231,Little Baby Bum: Nursery Rhyme Friends,Movie,NaN,NaN,NaN,2016,NaN,NaN,Movies
6232,A Young Doctor's Notebook and Other Stories,TV Show,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,NaN,TV-MA,"British TV Shows, TV Comedies, TV Dramas"
6233,Friends,TV Show,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,NaN,TV-14,"Classic & Cult TV, TV Comedies"

In [5]:
netflix_all = netflix_all.rename(columns={"listed_in": "genre"})
netflix_all

,title,type,director,cast,country,release_year,date_added,rating,genre
0,Norm of the North: King Sized Adventure,Movie,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,"September 9, 2019",TV-PG,"Children & Family Movies, Comedies"
1,Jandino: Whatever it Takes,Movie,NaN,Jandino Asporaat,United Kingdom,2016,"September 9, 2016",TV-MA,Stand-Up Comedy
2,Transformers Prime,TV Show,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,"September 8, 2018",TV-Y7-FV,Kids' TV
3,Transformers: Robots in Disguise,TV Show,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,"September 8, 2018",TV-Y7,Kids' TV
4,#realityhigh,Movie,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,"September 8, 2017",TV-14,Comedies
...,...,...,...,...,...,...,...,...,...
6229,Red vs. Blue,TV Show,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NaN,NR,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
6230,Maron,TV Show,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,NaN,TV-MA,TV Comedies
6231,Little Baby Bum: Nursery Rhyme Friends,Movie,NaN,NaN,NaN,2016,NaN,NaN,Movies
6232,A Young Doctor's Notebook and Other Stories,TV Show,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,NaN,TV-MA,"British TV Shows, TV Comedies, TV Dramas"
6233,Friends,TV Show,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,NaN,TV-14,"Classic & Cult TV, TV Comedies"

In [11]:
# Read in Rotten Tomatoes CSV
RT = pd.read_csv("Rottentomatoes/rottentomatoes.csv")
RT = RT[["title", "rating"]].copy()
RT = RT.rename(columns={"rating": "score"})

In [13]:
# Read in IMDB CSV
IMDB = pd.read_csv("show.csv")
IMDB = IMDB[["title", "star_rating"]].copy()
IMDB = IMDB.rename(columns={"star_rating": "score"})

In [ ]:
# Merge the two dataframes

In [11]:
netflix_all.to_csv("Output/all_netflix_data.csv", encoding="utf-8", header=True)