In [25]:
# Dependencies
import pandas as pd

In [26]:
# Read in Kaggle dataset
netflix_all = pd.read_csv('netflix_titles.csv')
netflix_all.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [27]:
netflix_all = netflix_all[["title", "type", "director", "cast", "country", "release_year", "date_added", "rating", "listed_in"]].copy()
netflix_all

,title,type,director,cast,country,release_year,date_added,rating,listed_in
0,Norm of the North: King Sized Adventure,Movie,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,"September 9, 2019",TV-PG,"Children & Family Movies, Comedies"
1,Jandino: Whatever it Takes,Movie,NaN,Jandino Asporaat,United Kingdom,2016,"September 9, 2016",TV-MA,Stand-Up Comedy
2,Transformers Prime,TV Show,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,"September 8, 2018",TV-Y7-FV,Kids' TV
3,Transformers: Robots in Disguise,TV Show,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,"September 8, 2018",TV-Y7,Kids' TV
4,#realityhigh,Movie,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,"September 8, 2017",TV-14,Comedies
...,...,...,...,...,...,...,...,...,...
6229,Red vs. Blue,TV Show,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NaN,NR,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
6230,Maron,TV Show,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,NaN,TV-MA,TV Comedies
6231,Little Baby Bum: Nursery Rhyme Friends,Movie,NaN,NaN,NaN,2016,NaN,NaN,Movies
6232,A Young Doctor's Notebook and Other Stories,TV Show,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,NaN,TV-MA,"British TV Shows, TV Comedies, TV Dramas"
6233,Friends,TV Show,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,NaN,TV-14,"Classic & Cult TV, TV Comedies"

In [35]:
netflix_all = netflix_all.rename(columns={"listed_in": "genre",
                                         "rating": "viewer_rating"})
netflix_all.drop_duplicates("title", inplace=True)
netflix_all

,title,type,director,cast,country,release_year,date_added,viewer_rating,genre
0,Stripes,Movie,Ivan Reitman,"Bill Murray, Harold Ramis, Warren Oates, P.J. ...",United States,1981,"September 1, 2019",R,"Classic Movies, Comedies, Cult Movies"
1,All About Nina,Movie,Eva Vives,"Mary Elizabeth Winstead, Common, Kate del Cast...",United States,2018,"March 18, 2019",R,"Comedies, Dramas, Independent Movies"
2,The Boy Who Harnessed the Wind,Movie,Chiwetel Ejiofor,"Maxwell Simba, Chiwetel Ejiofor, Aïssa Maïga, ...","United Kingdom, Malawi",2019,"March 1, 2019",TV-14,"Children & Family Movies, Dramas, Independent ..."
3,The Autopsy of Jane Doe,Movie,André Øvredal,"Emile Hirsch, Brian Cox, Ophelia Lovibond, Mic...","United Kingdom, United States",2016,"December 30, 2018",R,"Horror Movies, Independent Movies, Thrillers"
4,Junebug,Movie,Phil Morrison,"Amy Adams, Embeth Davidtz, Ben McKenzie, Aless...",United States,2005,"March 1, 2019",R,"Comedies, Dramas, Independent Movies"
...,...,...,...,...,...,...,...,...,...
304,Dear White People,TV Show,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,2019,"August 2, 2019",TV-MA,"TV Comedies, TV Dramas"
305,Between,TV Show,NaN,"Jennette McCurdy, Jesse Carere, Ryan Allen, Ju...",Canada,2016,"July 1, 2016",TV-14,"International TV Shows, TV Dramas, TV Mysteries"
306,Another Life,TV Show,NaN,"Katee Sackhoff, Justin Chatwin, Samuel Anderso...",United States,2019,"July 25, 2019",TV-MA,"TV Action & Adventure, TV Dramas, TV Mysteries"
307,The I-Land,TV Show,NaN,"Natalie Martinez, Kate Bosworth, Ronald Peet, ...",United States,2019,"September 12, 2019",TV-MA,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ..."
308,Bill Nye Saves the World,TV Show,NaN,"Bill Nye, Karlie Kloss, Derek Muller, Emily Ca...",United States,2018,"May 11, 2018",TV-14,Stand-Up Comedy & Talk Shows

In [37]:
# Read in Rotten Tomatoes CSV
RT = pd.read_csv("../Rottentomatoes/rottentomatoes.csv")
RT = RT[["title", "rating"]].copy()
RT

                                  title  rating
0                               Stripes     8.6
1                        All About Nina     8.6
2        The Boy Who Harnessed the Wind     8.6
3                      Cookie's Fortune     8.6
4               The Autopsy of Jane Doe     8.6
..                                  ...     ...
245                       Strong Island    10.0
246                            Shirkers    10.0
247               The Square (Al Midan)    10.0
248  Crip Camp: A Disability Revolution    10.0
249                Knock Down the House    10.0

[250 rows x 2 columns]

In [38]:
# Read in IMDB CSV
IMDB = pd.read_csv("../IMDB/show.csv")
IMDB = IMDB[["title", "star_rating"]].copy()
IMDB = IMDB.rename(columns={"star_rating": "rating"})

In [39]:
# Merge the two dataframes
merged = pd.merge(RT, IMDB, how="outer")
merged

                              title  rating
0                           Stripes     8.6
1                    All About Nina     8.6
2    The Boy Who Harnessed the Wind     8.6
3                  Cookie's Fortune     8.6
4           The Autopsy of Jane Doe     8.6
..                              ...     ...
408                Haters Back Off!     6.0
409                    Another Life     4.9
410                      The I-Land     4.5
411        Bill Nye Saves the World     3.6
412                      Tiger King     7.7

[413 rows x 2 columns]

In [40]:
anotha_one = pd.merge(merged, netflix_all, on="title", how="inner")
anotha_one

,title,rating,type,director,cast,country,release_year,date_added,viewer_rating,genre
0,Stripes,8.6,Movie,Ivan Reitman,"Bill Murray, Harold Ramis, Warren Oates, P.J. ...",United States,1981,"September 1, 2019",R,"Classic Movies, Comedies, Cult Movies"
1,All About Nina,8.6,Movie,Eva Vives,"Mary Elizabeth Winstead, Common, Kate del Cast...",United States,2018,"March 18, 2019",R,"Comedies, Dramas, Independent Movies"
2,The Boy Who Harnessed the Wind,8.6,Movie,Chiwetel Ejiofor,"Maxwell Simba, Chiwetel Ejiofor, Aïssa Maïga, ...","United Kingdom, Malawi",2019,"March 1, 2019",TV-14,"Children & Family Movies, Dramas, Independent ..."
3,The Autopsy of Jane Doe,8.6,Movie,André Øvredal,"Emile Hirsch, Brian Cox, Ophelia Lovibond, Mic...","United Kingdom, United States",2016,"December 30, 2018",R,"Horror Movies, Independent Movies, Thrillers"
4,Junebug,8.6,Movie,Phil Morrison,"Amy Adams, Embeth Davidtz, Ben McKenzie, Aless...",United States,2005,"March 1, 2019",R,"Comedies, Dramas, Independent Movies"
...,...,...,...,...,...,...,...,...,...,...
304,Dear White People,6.2,TV Show,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,2019,"August 2, 2019",TV-MA,"TV Comedies, TV Dramas"
305,Between,6.0,TV Show,NaN,"Jennette McCurdy, Jesse Carere, Ryan Allen, Ju...",Canada,2016,"July 1, 2016",TV-14,"International TV Shows, TV Dramas, TV Mysteries"
306,Another Life,4.9,TV Show,NaN,"Katee Sackhoff, Justin Chatwin, Samuel Anderso...",United States,2019,"July 25, 2019",TV-MA,"TV Action & Adventure, TV Dramas, TV Mysteries"
307,The I-Land,4.5,TV Show,NaN,"Natalie Martinez, Kate Bosworth, Ronald Peet, ...",United States,2019,"September 12, 2019",TV-MA,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ..."
308,Bill Nye Saves the World,3.6,TV Show,NaN,"Bill Nye, Karlie Kloss, Derek Muller, Emily Ca...",United States,2018,"May 11, 2018",TV-14,Stand-Up Comedy & Talk Shows

In [43]:
netflix_all = anotha_one[["title", "type", "director", "cast", "country", "release_year", "date_added", "viewer_rating", "genre"]].copy()
netflix_all

,title,type,director,cast,country,release_year,date_added,viewer_rating,genre
0,Stripes,Movie,Ivan Reitman,"Bill Murray, Harold Ramis, Warren Oates, P.J. ...",United States,1981,"September 1, 2019",R,"Classic Movies, Comedies, Cult Movies"
1,All About Nina,Movie,Eva Vives,"Mary Elizabeth Winstead, Common, Kate del Cast...",United States,2018,"March 18, 2019",R,"Comedies, Dramas, Independent Movies"
2,The Boy Who Harnessed the Wind,Movie,Chiwetel Ejiofor,"Maxwell Simba, Chiwetel Ejiofor, Aïssa Maïga, ...","United Kingdom, Malawi",2019,"March 1, 2019",TV-14,"Children & Family Movies, Dramas, Independent ..."
3,The Autopsy of Jane Doe,Movie,André Øvredal,"Emile Hirsch, Brian Cox, Ophelia Lovibond, Mic...","United Kingdom, United States",2016,"December 30, 2018",R,"Horror Movies, Independent Movies, Thrillers"
4,Junebug,Movie,Phil Morrison,"Amy Adams, Embeth Davidtz, Ben McKenzie, Aless...",United States,2005,"March 1, 2019",R,"Comedies, Dramas, Independent Movies"
...,...,...,...,...,...,...,...,...,...
304,Dear White People,TV Show,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,2019,"August 2, 2019",TV-MA,"TV Comedies, TV Dramas"
305,Between,TV Show,NaN,"Jennette McCurdy, Jesse Carere, Ryan Allen, Ju...",Canada,2016,"July 1, 2016",TV-14,"International TV Shows, TV Dramas, TV Mysteries"
306,Another Life,TV Show,NaN,"Katee Sackhoff, Justin Chatwin, Samuel Anderso...",United States,2019,"July 25, 2019",TV-MA,"TV Action & Adventure, TV Dramas, TV Mysteries"
307,The I-Land,TV Show,NaN,"Natalie Martinez, Kate Bosworth, Ronald Peet, ...",United States,2019,"September 12, 2019",TV-MA,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ..."
308,Bill Nye Saves the World,TV Show,NaN,"Bill Nye, Karlie Kloss, Derek Muller, Emily Ca...",United States,2018,"May 11, 2018",TV-14,Stand-Up Comedy & Talk Shows

In [44]:
netflix_all.to_csv("all_netflix_data.csv", encoding="utf-8", header=True)