In [10]:
# Dependencies
import requests
from bs4 import BeautifulSoup as bs
from splinter import Browser
import pandas as pd

In [11]:
# Create path and browser
executable_path={'executable_path': 'chromedriver.exe'}
browser=Browser('chrome', **executable_path, headless=False)

# URL of page to be scraped
url="https://editorial.rottentomatoes.com/guide/best-netflix-movies-to-watch-right-now/"
browser.visit(url)

In [ ]:
# Loop the results to find title, year, rating
dict={}
mov=[]
for x in range(3):
    html = browser.html
    soup=bs(html, 'html.parser')
    movies=soup.find_all('div',class_="article_movie_title")
    
    for movie in movies:
        title=movie.find('a').text
        year=movie.find('span',class_='subtle start-year').text
        year=int(year[1:5])
        rating=movie.find('span',class_='tMeterScore').text
        rating=float(rating[:2])/10
        dict={'title':title,
             'year':year,
             'rating':rating}
        mov.append(dict)
        print(dict)
        try:
            browser.find_by_name('  Next ').click()
        except:
            pass

In [50]:
# Create a dataframe and export:
df=pd.DataFrame(mov)
#df.to_csv('df.csv')
df

                              title  year  rating
0                           Stripes  1981     8.6
1                    All About Nina  2018     8.6
2    The Boy Who Harnessed the Wind  2019     8.6
3                  Cookie's Fortune  1999     8.6
4           The Autopsy of Jane Doe  2016     8.6
..                              ...   ...     ...
295             There Will Be Blood  2007     9.1
296                      Green Room  2016     9.1
297                       Good Time  2017     9.1
298                     The Fighter  2010     9.1
299                   A Ghost Story  2017     9.1

[300 rows x 3 columns]